In [15]:
import hexdump
import numpy as np

In [2]:
import struct
file_in = '123.gr2'
fd = open(file_in,'rb')
numpy_data = np.fromfile(fd, dtype = np.dtype('B'))

FileNotFoundError: [Errno 2] No such file or directory: '123.gr2'

In [3]:
l= list(i*i for i in range(0,500) if i%5==0)

In [4]:
import numpy as np
import urllib.request

page = urllib.request.urlopen("http://mgr.imces.ru/stdpub/mgr-baikal/hsg-irkutsk/48E8746F34325647_170926_092325.gr2")
f = open("test.txt", "w")
content = page.read()
numpy_data = np.frombuffer(content, dtype = np.dtype('B')).reshape(int(len(content)/12),12)
f.close()

print(numpy_data)



[[ 71  82  48  50  72 232 116 111  52  50  86  71]
 [ 28 155 116 221  96   3 222   0 184   0 201   0]
 [ 38 155 116 221 194   3  30   1 246   0 223   0]
 [ 48 155 116 221 112   3 238   0 208   0 204   0]
 [ 58 155 116 221 157   3 212   0 175   0 203   0]
 [ 68 155 116 221  45   4 222   0  15   1 204   0]
 [ 78 155 116 221  28   5  32   1 103   1   3   1]
 [ 88 155 116 221  49   3 201   0 159   0 209   0]
 [ 98 155 116 221 105   2  54   1 100   0 219   0]
 [108 155 116 221 140   2 233   0 131   0 214   0]
 [118 155 116 221 149   2  66   1 103   0 206   0]
 [128 155 116 221  23   3  55   1 140   0 243   0]
 [138 155 116 221 113   3 224   0 193   0 238   0]
 [148 155 116 221  44   3 138   1 164   0  33   1]
 [158 155 116 221  23   3 207   0 149   0 213   0]
 [168 155 116 221 117   3 206   0 189   0 212   0]
 [178 155 116 221  96   3 220   0 205   0 201   0]]


In [5]:
a=np.array(numpy_data, dtype=np.uint32)
s=0
for i in range(3,-1,-1):
    s = s+a[4,i]*pow(16,i*2)
    

In [6]:
from datetime import datetime
datetime.fromtimestamp(s-2209032000).strftime("%A, %B %d, %Y %I:%M:%S")


'Tuesday, September 26, 2017 04:24:10'

In [10]:
import struct
testBytes = b'\x00\x01\x00\x02'
testResult = struct.unpack('<HH', content)
print (testResult)

error: unpack requires a buffer of 4 bytes

In [14]:
testBytes = b'\xF1\x10'
for i in range(len(content)):
    print(int.from_bytes(content, byteorder='big',signed=True))
    

53202332605298943339605997551300403504133100558275005374257573069006281253073272075049536233895293928193280815038519950371676269238692289979991067735921014054377892532869568955463514075641998173352229823915563401992467806025209683624028476562150778385001054274062283291477022300296270021288450254841893683857287264883352378930913568337570379447582405759568264748071800838877317753449214150822269147359467539090460621966516393247538487277394007987364699025323969191375639195785844459940399360
53202332605298943339605997551300403504133100558275005374257573069006281253073272075049536233895293928193280815038519950371676269238692289979991067735921014054377892532869568955463514075641998173352229823915563401992467806025209683624028476562150778385001054274062283291477022300296270021288450254841893683857287264883352378930913568337570379447582405759568264748071800838877317753449214150822269147359467539090460621966516393247538487277394007987364699025323969191375639195785844459940399360
5320233260529894

In [ ]:
z=np.array(content[0:4])

In [ ]:
int.from_bytes(z, byteorder='little',signed=True)