In [83]:
import numpy as np
from datetime import datetime
import numpy as np
import urllib.request

In [298]:
page = urllib.request.urlopen("http://mgr.imces.ru/stdpub/mgr-baikal/hsg-irkutsk/48E8746F34325647_170926_092325.gr2")
f = open("test.txt", "w")
content = page.read()
numpy_data_polojitelnie = np.frombuffer(content, dtype = np.dtype('B')).reshape(int(len(content)/12),12)
numpy_data_otrisatelnie = np.frombuffer(content, dtype = np.dtype('b')).reshape(int(len(content)/12),12)
f.close()
gr2 = 12
length_column = int(len(content) / gr2) -  1 #(вычитаем первую строку так как в этой строке  допольнителные данные )
# print(numpy_data_polojitelnie)
# print(numpy_data_otrisatelnie)

In [420]:
numpy_date = np.array(numpy_data_polojitelnie[1:,:4], dtype=np.uint32)
numpy_H1_amp_count = numpy_data_polojitelnie[1:,4:6]
numpy_H1_amp_amplituda = numpy_data_otrisatelnie[1:,6:8]
numpy_H2_amp_count = numpy_data_polojitelnie[1:,8:10]
numpy_H2_amplituda = numpy_data_otrisatelnie[1:,10:12]

# print (numpy_date)

print(numpy_H1_amp_count)
#print (numpy_H1_amplituda)

print(numpy_H2_amp_count)
# print(numpy_H2_amplituda)


[[ 96   3]
 [194   3]
 [112   3]
 [157   3]
 [ 45   4]
 [ 28   5]
 [ 49   3]
 [105   2]
 [140   2]
 [149   2]
 [ 23   3]
 [113   3]
 [ 44   3]
 [ 23   3]
 [117   3]
 [ 96   3]]
[[184   0]
 [246   0]
 [208   0]
 [175   0]
 [ 15   1]
 [103   1]
 [159   0]
 [100   0]
 [131   0]
 [103   0]
 [140   0]
 [193   0]
 [164   0]
 [149   0]
 [189   0]
 [205   0]]


In [337]:
# Funksiya kotoraya vozrshayet vremya v sekundax iz pervoy stolbsa
def date_v_sekundax(massiv): 
    
    s = np.zeros(length_column, dtype='uint64')
    for i in range(length_column):
        s[i] = massiv[i,3] * (pow(16,6)) +  massiv[i,1] * (pow(16,4)) +massiv[i,2] * (pow(16,2)) +  massiv[i,0]
    return s      

In [364]:
array_date_v_sekundax= date_v_sekundax(numpy_date)

In [365]:
array_date_v_sekundax

array([3717952540, 3717952550, 3717952560, 3717952570, 3717952580,
       3717952590, 3717952600, 3717952610, 3717952620, 3717952630,
       3717952640, 3717952650, 3717952660, 3717952670, 3717952680,
       3717952690], dtype=uint64)

In [421]:
# Funksiya kotoraya vozrshayet vremya v obichnom formate
def data_obichniy_format(massiv): 
    s = np.zeros(length_column, dtype='<U36') #"<U36"dlina simvolov
    for i in range(len(massiv)):
        s[i] = datetime.fromtimestamp(massiv[i] -2209032000).strftime("%A, %B %d, %Y %I:%M:%S")
    return s    

In [422]:
array_data_obichniy_format = data_obichniy_format(array_date_v_sekundax)

In [435]:
array_data_obichniy_format

array(['Wednesday, October 25, 2017 03:35:40',
       'Wednesday, October 25, 2017 03:35:50',
       'Wednesday, October 25, 2017 03:36:00',
       'Wednesday, October 25, 2017 03:36:10',
       'Wednesday, October 25, 2017 03:36:20',
       'Wednesday, October 25, 2017 03:36:30',
       'Wednesday, October 25, 2017 03:36:40',
       'Wednesday, October 25, 2017 03:36:50',
       'Wednesday, October 25, 2017 03:37:00',
       'Wednesday, October 25, 2017 03:37:10',
       'Wednesday, October 25, 2017 03:37:20',
       'Wednesday, October 25, 2017 03:37:30',
       'Wednesday, October 25, 2017 03:37:40',
       'Wednesday, October 25, 2017 03:37:50',
       'Wednesday, October 25, 2017 03:38:00',
       'Wednesday, October 25, 2017 03:38:10'], dtype='<U36')

In [436]:
# Funksiya obyedinyayet 2 stolbsa i vozvrashayet massiv desyaterichnom vide
def func_join_2_column(massiv): 
    s = np.zeros(length_column, dtype='uint32')
    for i in range(length_column):
        s[i] = massiv[i,0]  +  massiv[i,1] * 16
    return s      

In [438]:
func_join_2_column(numpy_H2_amp_count)

array([184, 246, 208, 175,  31, 119, 159, 100, 131, 103, 140, 193, 164,
       149, 189, 205], dtype=uint32)

In [439]:
numpy_H2_amp_count

array([[184,   0],
       [246,   0],
       [208,   0],
       [175,   0],
       [ 15,   1],
       [103,   1],
       [159,   0],
       [100,   0],
       [131,   0],
       [103,   0],
       [140,   0],
       [193,   0],
       [164,   0],
       [149,   0],
       [189,   0],
       [205,   0]], dtype=uint8)