In [109]:
import hexdump
import numpy as np

In [4]:
import struct
file_in = '123.gr2'
fd = open(file_in,'rb')
numpy_data = np.fromfile(fd, dtype = np.dtype('b'))

In [5]:
l= list(i*i for i in range(0,500) if i%5==0)

In [10]:
import numpy as np
import urllib.request

page = urllib.request.urlopen("http://mgr.imces.ru/stdpub/mgr-baikal/hsg-irkutsk/48E8746F34325647_170926_092325.gr2")
f = open("test.txt", "w")
content = page.read()
numpy_data = np.frombuffer(content, dtype = np.dtype('B')).reshape(int(len(content)/12),12)
numpy_data_1 = np.frombuffer(content, dtype = np.dtype('b')).reshape(int(len(content)/12),12)

f.close()

print(numpy_data)
print(numpy_data_1)

numpy_date = np.array(numpy_data[1:,:4], dtype=np.uint32)
numpy_H1_amplituda = numpy_data[1:,4:6]
numpy_H1_amp_count = numpy_data[1:,6:8]
numpy_H2_amplituda = numpy_data[1:,8:10]
numpy_H2_amp_count = numpy_data[1:,10:12]
 

[[ 71  82  48  50  72 232 116 111  52  50  86  71]
 [ 28 155 116 221  96   3 222   0 184   0 201   0]
 [ 38 155 116 221 194   3  30   1 246   0 223   0]
 [ 48 155 116 221 112   3 238   0 208   0 204   0]
 [ 58 155 116 221 157   3 212   0 175   0 203   0]
 [ 68 155 116 221  45   4 222   0  15   1 204   0]
 [ 78 155 116 221  28   5  32   1 103   1   3   1]
 [ 88 155 116 221  49   3 201   0 159   0 209   0]
 [ 98 155 116 221 105   2  54   1 100   0 219   0]
 [108 155 116 221 140   2 233   0 131   0 214   0]
 [118 155 116 221 149   2  66   1 103   0 206   0]
 [128 155 116 221  23   3  55   1 140   0 243   0]
 [138 155 116 221 113   3 224   0 193   0 238   0]
 [148 155 116 221  44   3 138   1 164   0  33   1]
 [158 155 116 221  23   3 207   0 149   0 213   0]
 [168 155 116 221 117   3 206   0 189   0 212   0]
 [178 155 116 221  96   3 220   0 205   0 201   0]]
[[  71   82   48   50   72  -24  116  111   52   50   86   71]
 [  28 -101  116  -35   96    3  -34    0  -72    0  -55    0]
 [  38

In [2]:
# numpy_date  
# numpy_H1_amplituda  
# numpy_H1_amp_count  
# numpy_H2_amplituda  
# numpy_H2_amp_count  

In [3]:
def HextoInt(x,Count_of_Column):
    s=0
    for i in range(Count_of_Column-1,-1,-1):
        s = s+numpy_date[Count_of_Column,i]*pow(16,i*2)
    return s

In [6]:
from datetime import datetime
datetime.fromtimestamp(HextoInt(numpy_date[0],4)-2209032000).strftime("%A, %B %d, %Y %I:%M:%S")


'Tuesday, September 26, 2017 04:24:20'

In [15]:
HextoInt(numpy_H1_amp_count[0],2)

39728

In [111]:
numpy_date[1]

array([        38, 4294967195,        116, 4294967261], dtype=uint32)

In [136]:
arr = np.fromfile('12.gr2', dtype='<i1')
arr1 = np.fromfile('12.gr2', dtype=np.int16)

In [137]:
arr.reshape(17,12)


array([[  71,   82,   48,   50,   72,  -24,  116,  111,   52,   50,   86,
          71],
       [  28, -101,  116,  -35,   96,    3,  -34,    0,  -72,    0,  -55,
           0],
       [  38, -101,  116,  -35,  -62,    3,   30,    1,  -10,    0,  -33,
           0],
       [  48, -101,  116,  -35,  112,    3,  -18,    0,  -48,    0,  -52,
           0],
       [  58, -101,  116,  -35,  -99,    3,  -44,    0,  -81,    0,  -53,
           0],
       [  68, -101,  116,  -35,   45,    4,  -34,    0,   15,    1,  -52,
           0],
       [  78, -101,  116,  -35,   28,    5,   32,    1,  103,    1,    3,
           1],
       [  88, -101,  116,  -35,   49,    3,  -55,    0,  -97,    0,  -47,
           0],
       [  98, -101,  116,  -35,  105,    2,   54,    1,  100,    0,  -37,
           0],
       [ 108, -101,  116,  -35, -116,    2,  -23,    0, -125,    0,  -42,
           0],
       [ 118, -101,  116,  -35, -107,    2,   66,    1,  103,    0,  -50,
           0],
       [-128, -101,  

In [140]:
z = arr[::-1].reshape(17
                  ,12)


In [152]:
z

array([[   0,  -55,    0,  -51,    0,  -36,    3,   96,  -35,  116, -101,
         -78],
       [   0,  -44,    0,  -67,    0,  -50,    3,  117,  -35,  116, -101,
         -88],
       [   0,  -43,    0, -107,    0,  -49,    3,   23,  -35,  116, -101,
         -98],
       [   1,   33,    0,  -92,    1, -118,    3,   44,  -35,  116, -101,
        -108],
       [   0,  -18,    0,  -63,    0,  -32,    3,  113,  -35,  116, -101,
        -118],
       [   0,  -13,    0, -116,    1,   55,    3,   23,  -35,  116, -101,
        -128],
       [   0,  -50,    0,  103,    1,   66,    2, -107,  -35,  116, -101,
         118],
       [   0,  -42,    0, -125,    0,  -23,    2, -116,  -35,  116, -101,
         108],
       [   0,  -37,    0,  100,    1,   54,    2,  105,  -35,  116, -101,
          98],
       [   0,  -47,    0,  -97,    0,  -55,    3,   49,  -35,  116, -101,
          88],
       [   1,    3,    1,  103,    1,   32,    5,   28,  -35,  116, -101,
          78],
       [   0,  -52,  

In [155]:
z  = np.array(z,dtype='<i4')

In [156]:
z

array([[   0,  -55,    0,  -51,    0,  -36,    3,   96,  -35,  116, -101,
         -78],
       [   0,  -44,    0,  -67,    0,  -50,    3,  117,  -35,  116, -101,
         -88],
       [   0,  -43,    0, -107,    0,  -49,    3,   23,  -35,  116, -101,
         -98],
       [   1,   33,    0,  -92,    1, -118,    3,   44,  -35,  116, -101,
        -108],
       [   0,  -18,    0,  -63,    0,  -32,    3,  113,  -35,  116, -101,
        -118],
       [   0,  -13,    0, -116,    1,   55,    3,   23,  -35,  116, -101,
        -128],
       [   0,  -50,    0,  103,    1,   66,    2, -107,  -35,  116, -101,
         118],
       [   0,  -42,    0, -125,    0,  -23,    2, -116,  -35,  116, -101,
         108],
       [   0,  -37,    0,  100,    1,   54,    2,  105,  -35,  116, -101,
          98],
       [   0,  -47,    0,  -97,    0,  -55,    3,   49,  -35,  116, -101,
          88],
       [   1,    3,    1,  103,    1,   32,    5,   28,  -35,  116, -101,
          78],
       [   0,  -52,  