In [83]:
import numpy as np
from datetime import datetime
import numpy as np
import urllib.request

In [485]:
page = urllib.request.urlopen("http://mgr.imces.ru/stdpub/mgr-baikal/hsg-irkutsk/48E8746F34325647_171025_162506.gr2")
f = open("test.txt", "w")
content = page.read()
numpy_data_polojitelnie = np.frombuffer(content, dtype = np.dtype('B')).reshape(int(len(content)/12),12)
numpy_data_otrisatelnie = np.frombuffer(content, dtype = np.dtype('b')).reshape(int(len(content)/12),12)
f.close()
gr2 = 12
length_column = int(len(content) / gr2) -  1 #(вычитаем первую строку так как в этой строке  допольнителные данные )
# print(numpy_data_polojitelnie)
# print(numpy_data_otrisatelnie)

In [492]:
print (np.frombuffer(content, dtype = np.dtype('B')).reshape(int(len(content)/12),12))

[[ 71  82  48 ...  50  86  71]
 [212  57 155 ...   0 210   0]
 [ 16  58 155 ...   0 221   0]
 ...
 [ 72 107 155 ...   0 202   0]
 [132 107 155 ...   0   6   1]
 [192 107 155 ...   0 200   0]]


In [499]:
numpy_date = np.array(numpy_data_polojitelnie[1:,:4], dtype=np.uint32)
numpy_H1_amp_count = numpy_data_polojitelnie[1:,4:6]
numpy_H1_amplituda = numpy_data_polojitelnie[1:,6:8]
numpy_H2_amp_count = numpy_data_polojitelnie[1:,8:10]
numpy_H2_amplituda = numpy_data_polojitelnie[1:,10:12]

# print (numpy_date)

# print(numpy_H1_amp_count)
#print (numpy_H1_amplituda)

# print(numpy_H2_amp_count)
print(numpy_H2_amplituda)


[[210   0]
 [221   0]
 [212   0]
 [  0   1]
 [200   0]
 [205   0]
 [203   0]
 [203   0]
 [205   0]
 [211   0]
 [214   0]
 [215   0]
 [206   0]
 [ 12   1]
 [239   0]
 [232   0]
 [209   0]
 [201   0]
 [202   0]
 [217   1]
 [209   0]
 [204   0]
 [207   0]
 [206   0]
 [202   0]
 [210   0]
 [200   0]
 [229   0]
 [202   0]
 [ 25   1]
 [205   0]
 [224   0]
 [208   0]
 [  8   1]
 [ 75   1]
 [204   0]
 [203   0]
 [215   0]
 [218   0]
 [204   0]
 [202   0]
 [224   0]
 [ 51   1]
 [201   0]
 [202   0]
 [215   0]
 [211   0]
 [201   0]
 [  0   2]
 [200   0]
 [203   0]
 [102   1]
 [210   0]
 [205   0]
 [211   0]
 [209   0]
 [213   0]
 [121   1]
 [172   1]
 [ 77   1]
 [238   0]
 [216   0]
 [ 34   1]
 [141   1]
 [ 84   1]
 [  0   0]
 [225   0]
 [ 52   1]
 [  0   0]
 [ 46   1]
 [ 24   1]
 [212   0]
 [201   0]
 [  0   0]
 [  0   0]
 [117   3]
 [209   0]
 [218   0]
 [  0   0]
 [204   0]
 [225   0]
 [106   1]
 [224   0]
 [  0   0]
 [253   0]
 [  0   0]
 [ 82   1]
 [203   0]
 [  0   0]
 [  0   0]
 [204   0]

In [500]:
# Funksiya kotoraya vozrshayet vremya v sekundax iz pervoy stolbsa
def date_v_sekundax(massiv): 
    
    s = np.zeros(length_column, dtype='uint64')
    for i in range(length_column):
        s[i] = massiv[i,3] * (pow(16,6)) +  massiv[i,1] * (pow(16,4)) +massiv[i,2] * (pow(16,2)) +  massiv[i,0]
    return s      

In [501]:
array_date_v_sekundax= date_v_sekundax(numpy_date)

In [504]:
array_date_v_sekundax

array([3711540180, 3711605520, 3711605580, 3711605640, 3711605700,
       3711671040, 3711671100, 3711671160, 3711671220, 3711671280,
       3711736620, 3711736680, 3711736740, 3711736800, 3711802140,
       3711802200, 3711802260, 3711802320, 3711867660, 3711867720,
       3711867780, 3711867840, 3711867900, 3711933240, 3711933300,
       3711933360, 3711933420, 3711998760, 3711998820, 3711998880,
       3711998940, 3712064280, 3712064340, 3712064400, 3712064460,
       3712129800, 3712129860, 3712129920, 3712129980, 3712130040,
       3712195380, 3712195440, 3712195500, 3712195560, 3712260900,
       3712260960, 3712261020, 3712261080, 3712326420, 3712326480,
       3712326540, 3712326600, 3712391940, 3712392000, 3712392060,
       3712392120, 3712392180, 3712457520, 3712457580, 3712457640,
       3712457700, 3712523040, 3712523100, 3712523160, 3712523220,
       3712588560, 3712588620, 3712588680, 3712588740, 3712654080,
       3712654140, 3712654200, 3712654260, 3712654320, 3712719

In [508]:
# Funksiya kotoraya vozrshayet vremya v obichnom formate
def data_obichniy_format(massiv): 
    s = np.zeros(length_column, dtype='<U40') #"<U36"dlina simvolov
    for i in range(len(massiv)):
        s[i] = datetime.fromtimestamp(massiv[i] -2209032000).strftime("%A, %B %d, %Y %I:%M:%S")
    return s    

In [509]:
array_date_obichniy_format = data_obichniy_format(array_date_v_sekundax)

In [510]:
array_date_obichniy_format

array(['Saturday, August 12, 2017 10:23:00',
       'Sunday, August 13, 2017 04:32:00',
       'Sunday, August 13, 2017 04:33:00',
       'Sunday, August 13, 2017 04:34:00',
       'Sunday, August 13, 2017 04:35:00',
       'Sunday, August 13, 2017 10:44:00',
       'Sunday, August 13, 2017 10:45:00',
       'Sunday, August 13, 2017 10:46:00',
       'Sunday, August 13, 2017 10:47:00',
       'Sunday, August 13, 2017 10:48:00',
       'Monday, August 14, 2017 04:57:00',
       'Monday, August 14, 2017 04:58:00',
       'Monday, August 14, 2017 04:59:00',
       'Monday, August 14, 2017 05:00:00',
       'Tuesday, August 15, 2017 11:09:00',
       'Tuesday, August 15, 2017 11:10:00',
       'Tuesday, August 15, 2017 11:11:00',
       'Tuesday, August 15, 2017 11:12:00',
       'Wednesday, August 16, 2017 05:21:00',
       'Wednesday, August 16, 2017 05:22:00',
       'Wednesday, August 16, 2017 05:23:00',
       'Wednesday, August 16, 2017 05:24:00',
       'Wednesday, August 16, 2017 0

In [511]:
# Funksiya obyedinyayet 2 stolbsa i vozvrashayet massiv desyaterichnom vide
def func_join_2_column(massiv): 
    s = np.zeros(length_column, dtype='uint32')
    for i in range(length_column):
        s[i] = massiv[i,0]  +  massiv[i,1] * 16
    return s      

In [512]:
array_H1_amp_count = func_join_2_column(numpy_H1_amp_count)
array_H2_amp_count = func_join_2_column(numpy_H2_amp_count)
array_H1_amplituda = func_join_2_column(numpy_H1_amplituda)
array_H2_amplituda = func_join_2_column(numpy_H2_amplituda)

In [545]:
import numpy as np
import pandas as pd
# Creating a 2 dimensional numpy array
data= np.array([array_H1_amp_count,array_H2_amp_count,array_H1_amplituda,array_H2_amplituda])

dataset = pd.DataFrame({'Column1': array_date_obichniy_format, 'Column2':data[0],'Column3':data[1],'Column4':data[2],'Column5':data[3]})
print(dataset)

                                   Column1  Column2  Column3  Column4  Column5
0       Saturday, August 12, 2017 10:23:00      760       31       25      210
1         Sunday, August 13, 2017 04:32:00      666       22       21      221
2         Sunday, August 13, 2017 04:33:00      888       30      252      212
3         Sunday, August 13, 2017 04:34:00      753       14      217       16
4         Sunday, August 13, 2017 04:35:00      882       27       16      200
5         Sunday, August 13, 2017 10:44:00      944       18       45      205
6         Sunday, August 13, 2017 10:45:00      870       33       19      203
7         Sunday, August 13, 2017 10:46:00      904       27       18      203
8         Sunday, August 13, 2017 10:47:00      983       34       22      205
9         Sunday, August 13, 2017 10:48:00      948       38      229      211
10        Monday, August 14, 2017 04:57:00      767        3       20      214
11        Monday, August 14, 2017 04:58:00      699 